name: Toolchain

on:
  push:
    branches:
      - flutter/*

jobs:
  toolchain:
    name: Toolchain

    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/barteo/flutter-pi-toolchain/toolchain:flutter-1.22.5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y git
      
      - name: Install Depot Tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
