name: Toolchain

on:
  push:
    branches:
      - flutter/*

jobs:
  toolchain:
    name: Toolchain

    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/barteo/flutter-pi-toolchain/toolchain:flutter-1.22.5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y git wget

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      
      - name: Install Depot Tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Checkout Engine with source code dependencies
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        shell: bash
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          pwd
          ssh-add -l
          export PATH=`pwd`/depot_tools:$PATH
          mkdir engine
          cp main/.gclient engine/
          cd engine
          gclient sync
