name: Toolchain

on:
  push:
    branches:
      - flutter/*

jobs:
  toolchain:
    name: Toolchain

    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/barteo/flutter-pi-toolchain/toolchain:flutter-1.22.5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Test
        run: |
          ls -la /toolchain
          du -h /toolchain
