name: Engine

on:
  push:
    branches:
      - flutter/*

jobs:
  engine:
    name: Engine

    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/barteo/flutter-pi-toolchain/toolchain:flutter-1.22.6
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update
          apt install -y git lsb-release python sudo tzdata wget

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Install Depot Tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Test
        run: |
          git --version
          df -h

      - name: Checkout Engine with dependencies
        shell: bash
        run: |
          export SSH_AUTH_SOCK=/tmp/ssh_agent.sock
          mkdir -p /root/.ssh
          ssh-keyscan -H github.com >> /root/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          export PATH=`pwd`/depot_tools:$PATH
          mkdir engine
          cp main/.gclient engine/
          cd engine
          gclient sync
          cd src/flutter
          git config --global user.email "you@example.com"
          git remote add upstream git@github.com:flutter/engine.git
          git fetch upstream
          git checkout ae90085a8437c0ae94d6b5ad2741739ebc742cb4
          git cherry-pick f3cc39a5 # https://github.com/flutter/engine/pull/22560
          cd ..
          gclient sync -D
          ./build/install-build-deps.sh --no-prompt

      - name: Fix Sysroot symlinks
        run: |
          rm -r /sysroot/usr/lib/pkgconfig
          ln --symbolic --relative /sysroot/usr/lib/arm-linux-gnueabihf/pkgconfig /sysroot/usr/lib/pkgconfig
          ls -lL /sysroot/usr/lib/pkgconfig

      - name: Configure Engine
        run: |
          cd engine/src
          flutter/tools/gn \
            --target-sysroot /sysroot \
            --target-toolchain /toolchain \
            --target-triple arm-linux-gnueabihf \
            --linux-cpu arm \
            --runtime-mode debug \
            --embedder-for-target \
            --no-lto \
            --target-os linux \
            --arm-float-abi hard

      - name: Build Engine
        run: |
          ninja -C out/linux_debug_arm
