name: Sysroot

on:
  push:
    branches:
      - flutter/*

jobs:
  sysroot:
    name: Sysroot

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Sysroot
        run: |
          mkdir sysroot
          wget -q https://downloads.raspberrypi.org/raspios_full_armhf/images/raspios_full_armhf-2021-01-12/2021-01-11-raspios-buster-armhf-full.zip

      - name: Mount Sysroot
        run: |
          unzip 2021-01-11-raspios-buster-armhf-full.zip
          fdisk -l 2021-01-11-raspios-buster-armhf-full.img
          dd if=2021-01-11-raspios-buster-armhf-full.img of=sysroot.img bs=512 skip=532480 count=16269312
          fdisk -l sysroot.img
          sudo mount -v -t ext4 sysroot.img sysroot
          sudo du -h -d 1 sysroot

      - name: Prepare Sysroot
        run: |
          cd sysroot
          cd ..
          sudo du -h -d 1 sysroot
          ls -la sysroot
          df -h
          sudo du -h -d 2 sysroot

      - name: Prepare Sysroot 2
        run: |
          ls -lah
          sudo symlinks -c sysroot
          sudo tar -chzf sysroot.tar.gz sysroot

      - name: Prepare Sysroot 3
        run: |
          sudo umount sysroot
          ls -lah
          rm sysroot.img
          rm 2021-01-11-raspios-buster-armhf-full.zip
          rm 2021-01-11-raspios-buster-armhf-full.img
          df -h
          cd sysroot

      - name: Prepare Sysroot 4
        run: |
          tar -xzf ../sysroot.tar.gz

      - name: Prepare Sysroot 5
        run: |
          df -h
          cd ..
          rm sysroot.tar.gz
          ls -lah
          df -h

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile-sysroot
          registry: docker.pkg.github.com
          repository: barteo/flutter-pi-toolchain/sysroot
