name: Sysroot

on:
  push:
    branches:
      - flutter/*

jobs:
  sysroot:
    name: Sysroot

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Sysroot
        run: |
          mkdir sysroot
          wget https://downloads.raspberrypi.org/raspios_full_armhf/images/raspios_full_armhf-2021-01-12/2021-01-11-raspios-buster-armhf-full.zip
          unzip 2021-01-11-raspios-buster-armhf-full.zip
          fdisk -l 2021-01-11-raspios-buster-armhf-full.img
          dd if=2021-01-11-raspios-buster-armhf-full.img of=sysroot.img bs=512 skip=532480 count=16269312
          sudo mount -v -t ext4 sysroot.img sysroot
          ls -la sysroot
          ls -la

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile-sysroot
          registry: docker.pkg.github.com
          repository: barteo/flutter-pi-toolchain/sysroot
