name: Sysroot

on:
  push:
    branches:
      - flutter/*

jobs:
  sysroot:
    name: Sysroot

    runs-on: ubuntu-latest

    steps:
      - name: Prepare Sysroot
        run: |
          mkdir sysroot
          wget https://downloads.raspberrypi.org/raspios_full_armhf/images/raspios_full_armhf-2021-01-12/2021-01-11-raspios-buster-armhf-full.zip
          unzip 2021-01-11-raspios-buster-armhf-full.zip
          fdisk -l 2021-01-11-raspios-buster-armhf-full.img
          mount -v -o offset=272629760 -t ext4 2021-01-11-raspios-buster-armhf-full.img2 sysroot
          ls -la sysroot
