name: Sysroot

on:
  push:
    branches:
      - flutter/*

jobs:
  sysroot:
    name: Sysroot

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Sysroot
        run: |
          mkdir sysroot
          wget -q https://downloads.raspberrypi.org/raspios_full_armhf/images/raspios_full_armhf-2021-01-12/2021-01-11-raspios-buster-armhf-full.zip

      - name: Mount Sysroot
        run: |
          unzip 2021-01-11-raspios-buster-armhf-full.zip
          fdisk -l 2021-01-11-raspios-buster-armhf-full.img
          dd if=2021-01-11-raspios-buster-armhf-full.img of=sysroot.img bs=512 skip=532480 count=16269312
          fdisk -l sysroot.img
          sudo mount -v -t ext4 sysroot.img sysroot
          sudo du -h -d 1 sysroot

      - name: Prepare Sysroot
        run: |
          cd sysroot
          sudo rm -rf bin boot dev etc home media mnt opt proc root run sbin srv sys tmp var
          sudo rm -rf usr/share/fonts usr/share/doc usr/share/icons usr/share/libreoffice
          sudo rm -rf usr/lib/firmware usr/lib/jvm usr/lib/libreoffice usr/lib/node_modules usr/lib/pypy usr/lib/python3 usr/lib/scratch3
          cd ..
          sudo du -h -d 1 sysroot
          ls -la sysroot
          df -h
          sudo du -h -d 3 sysroot
          tar -chf sysroot.tar sysroot
          sudo umount sysroot
          ls -lah
          rm sysroot.img
          rm 2021-01-11-raspios-buster-armhf-full.zip
          rm 2021-01-11-raspios-buster-armhf-full.img
          df -h
          cd sysroot
          tar -xf ../sysroot.tar
          df -h
          cd ..
          rm sysroot.tar
          ls -lah
          df -h

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile-sysroot
          registry: docker.pkg.github.com
          repository: barteo/flutter-pi-toolchain/sysroot
