name: test

on:
  push:
    branches:
      - flutter/disabled

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          ls -la
