name: test

on:
  push:
    branches:
      - flutter/*

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install expect qemu-system-arm

      - name: Download Sysroot
        run: |
          wget -q https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-09-30/2019-09-26-raspbian-buster-lite.zip
          unzip 2019-09-26-raspbian-buster-lite.zip

      - name: Download Kernel
        run: |
          wget -q https://github.com/dhruvvyas90/qemu-rpi-kernel/raw/master/kernel-qemu-4.19.50-buster
          wget -q https://github.com/dhruvvyas90/qemu-rpi-kernel/raw/master/versatile-pb.dtb
          ls -lah

      - name: Install packages
        run: |
          chmod +x install-packages.exp
          ./install-packages.exp

      - name: Mount Sysroot
        run: |
          mkdir sysroot
          fdisk -l 2019-09-26-raspbian-buster-lite.img
          dd if=2019-09-26-raspbian-buster-lite.img of=sysroot.img bs=512 skip=532480 count=16269312
          fdisk -l sysroot.img
          sudo mount -v -t ext4 sysroot.img sysroot
          ls -la sysroot/lib
          sudo du -h -d 1 sysroot

      - name: Prepare Sysroot 1
        run: |
          cd sysroot
          ls -laL lib
          sudo rm -rf boot dev home media mnt proc root run srv sys tmp var
          cd ..
          sudo tar -czf sysroot.tar.gz sysroot

      - name: Prepare Sysroot 2
        run: |
          sudo umount sysroot
          ls -lah
          rm 2019-09-26-raspbian-buster-lite.zip
          rm 2019-09-26-raspbian-buster-lite.img
          rm sysroot.img
          df -h
          cd sysroot

      - name: Prepare Sysroot 3
        run: |
          ls -lah
          tar -xzf sysroot.tar.gz

      - name: Prepare Sysroot 4
        run: |
          df -h
          rm sysroot.tar.gz
          cd sysroot
          ls -la lib

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile-sysroot
          registry: docker.pkg.github.com
          repository: barteo/flutter-pi-toolchain/sysroot
          tag_with_ref: true
