name: test

on:
  push:
    branches:
      - flutter/*

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt install qemu-system-arm

      - name: Download Sysroot
        run: |
          wget http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-09-30/2019-09-26-raspbian-buster-lite.zip
          unzip 2019-09-26-raspbian-buster-lite.zip
          ls -lah

      - name: Test 2
        run: |
          qemu-system-arm \
            --machine versatilepb \
            --cpu arm1176 \
            --m 256m \
            --drive "format=raw,file=2019-09-26-raspbian-buster-lite.img" \
            --net nic --net user,hostfwd=tcp::5022-:22 \
            --dtb "${dtb}" \
            --kernel "${kernel}" \
            --append "rw earlyprintk loglevel=8 console=ttyAMA0,115200 dwc_otg.lpm_enable=0 root=/dev/sda2 rootwait panic=1" \
            --no-reboot \
            --display none \
            --serial mon:stdio

      - name: Fix permissions
        run: |
          chmod +x entrypoint.sh

#      - name: Run Docker Container
#        uses: docker://lukechilds/dockerpi
