name: test

on:
  push:
    branches:
      - flutter/*

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fix permissions
        run: |
          chmod +x entrypoint.sh

      - name: Run Docker Container
        uses: docker://lukechilds/dockerpi

      - name: Test
        run: |
          ps aux
